---
kind: Service
apiVersion: v1
metadata:
  name: test-app-sidecar-backend
  namespace: {{ TEST_APP_NAMESPACE_NAME }}
spec:
  selector:
    app: test-app-sidecar-backend
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test-app-pg
  labels:
    app: test-app-sidecar-backend
spec:
  serviceName: test-app-sidecar-backend
  selector:
    matchLabels:
      app: test-app-sidecar-backend
  template:
    metadata:
      labels:
        app: test-app-sidecar-backend
    spec:
      containers:
      - name: test-app-sidecar-backend
        image: {{ TEST_APP_PG_DOCKER_IMAGE }}
        imagePullPolicy: Always
        ports:
          - containerPort: 5432